<div id="add-item-modal" style="display:none;">
    <div class="modal-content">
        <form id="item-creation-form">
            <input id="item-parent" type="hidden" name="parent_id" />
            <label for="item-label">Label</label>
            <input id="item-label" type="text" name="label" required/>
            <label for="item-url">Target URL</label>
            <input id="item-url" type="text" name="target_url" />
            <button id="item-creation-submit" type="submit" hidden>submit</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
    ], function($, modal) {
        'use strict';

        let options = {
            type: 'slide',
            responsive: true,
            innerScroll: true,
            title: 'Create New Item',
            buttons: [{
                text: $.mage.__('Save'),
                class: '',
                click: function () {
                    $('#item-creation-submit').click();
                }
            }]
        };

        modal(options, $('#add-item-modal'));

        const form = $('#item-creation-form');

        form.on('submit', (e) => {
            e.preventDefault();
            e.stopPropagation();

            let formData = form.serializeArray();
            let item = {};

            formData.forEach(({name, value}) => {
                item[name] = value;
            })

            window.createItem(item);
            window.closeItemModal();
        })
    });
</script>
