<div id="add-item-modal" style="display:none;">
    <div class="modal-content">
        <form
            id="item-creation-form"
        >
            <label for="item-type">Item Type</label>
            <select id="item-type" name="menu_item_type">
                <option value="link">Link</option>
                <option value="category">Category</option>
                <option value="container">Container Item</option>
            </select>
            <label for="item-label">Label</label>
            <input id="item-label" type="text" name="label" />
            <label for="item-url">Target URL</label>
            <input id="item-url" type="text" name="target_url" />
            <label for="item-parent">Parent ID</label>
            <input id="item-parent" type="text" name="parent_id" />
        </form>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
    ], function($, modal) {
        'use strict';

        let options = {
            type: 'slide',
            responsive: true,
            innerScroll: true,
            title: 'Create New Item',
            buttons: [{
                text: $.mage.__('Save'),
                class: '',
                click: function () {
                    handleItemSave();
                }
            }]
        };

        modal(options, $('#add-item-modal'));

        const handleItemSave = function(e) {
            const form = $('#item-creation-form');

            let formData = form.serializeArray();
            let item = {};

            formData.forEach(({name, value}) => {
                item[name] = value;
            })

            window.createItem(item);

            $('#add-item-modal').modal('closeModal');
            form.trigger('reset');
        };
    });
</script>
